import { MEANING_LIBRARY } from "../maruPictureData";
import { NPC_SPOTS, SPOTS, archiveHouse, gateWall, terraces, westHouses } from "./layout";
import type { LanguagePack, PhonemeEntry } from "./types";

/**
 * Danish pack, set on the Nyhavn quay in Copenhagen.
 * VERIFICATION: spellings, glosses and grammar notes are standard Danish. Every IPA transcription and the
 * phoneme descriptions were written from general knowledge and are NOT checked against a pronunciation
 * dictionary or a native speaker. They are flagged `verified: false` and shown as such in the game.
 */

// Nyhavn façade colours: mustard, brick red, harbour blue, cream, orange, sage, rose, navy.
const FACADE = ["#f3d98b", "#e9a59c", "#9fc3de", "#f4ead2", "#f2b88c", "#b8d4bf", "#e7b6c4", "#9fb0cf"];
const ROOFS = ["#d98a7d", "#8d9bb0", "#b58e86"];

const vowel = (symbol: string, name: string, how: string, keywords: PhonemeEntry["keywords"], extra: Partial<PhonemeEntry> = {}): PhonemeEntry => ({
  symbol,
  kind: "vowel",
  name,
  how,
  keywords,
  ...extra,
});
const cons = (symbol: string, name: string, how: string, keywords: PhonemeEntry["keywords"], extra: Partial<PhonemeEntry> = {}): PhonemeEntry => ({
  symbol,
  kind: "consonant",
  name,
  how,
  keywords,
  ...extra,
});

export const da: LanguagePack = {
  id: "da",
  language: "da",
  chapter: { number: 2, title: "Navn" },
  name: "Danish",
  nativeName: "Dansk",
  city: "Copenhagen",
  district: "Nyhavn",
  intro:
    "You have just arrived at Nyhavn and you speak no Danish. Nobody will translate. Watch what people do, listen, write down the sounds, and work out what the words mean.",
  script: "latin",
  speech: { synth: "da-DK", recog: "da-DK", rate: 0.75, strict: true, testPhrase: "Goddag" },
  notation: {
    kind: "ipa",
    label: "IPA",
    help: "Write what you hear in IPA. Use the symbol keys below; stress, length and stød marks are optional.",
    keyboard: [
      "i",
      "y",
      "e",
      "ø",
      "ɛ",
      "œ",
      "a",
      "ɑ",
      "ɒ",
      "u",
      "o",
      "ɔ",
      "ʌ",
      "ə",
      "ɐ",
      "p",
      "t",
      "k",
      "b",
      "d",
      "g",
      "f",
      "v",
      "w",
      "s",
      "h",
      "j",
      "l",
      "m",
      "n",
      "ŋ",
      "ʁ",
      "ð",
      "ɪ",
      "ˀ",
      "ː",
      "ˈ",
    ],
    ignore: "ˈˌːˑˀʰ ./[]-‿",
    equivalent: [
      ["ɔ", "ʌ", "o", "ɒ"],
      ["ɛ", "e", "æ"],
      ["ɑ", "a"],
      ["ɐ", "ə"],
      ["b", "p"],
      ["d", "t", "ð"],
      ["g", "k", "ɡ"],
      ["ʁ", "r"],
      ["ɪ", "i"],
    ],
  },
  phonology: [
    vowel("i", "close front unrounded vowel", "Like the vowel in English “see”, but tenser and held steady (no glide to a y-sound).", [
      { written: "ti", sound: "tiˀ", gloss: "ten" },
      { written: "ni", sound: "niˀ", gloss: "nine" },
    ]),
    vowel(
      "y",
      "close front rounded vowel",
      "Say “ee” while rounding the lips as for “oo”. Same as German ü or French u.",
      [
        { written: "by", sound: "byˀ", gloss: "town" },
        { written: "ny", sound: "nyˀ", gloss: "new" },
      ],
      { confusableWith: ["i", "u"] }
    ),
    vowel("e", "close-mid front vowel", "Between “see” and “bed”. Often spelled e.", [{ written: "se", sound: "seˀ", gloss: "to see" }], {
      confusableWith: ["ɛ"],
    }),
    vowel("ɛ", "open-mid front vowel", "Close to the vowel in English “bed”. Spelled e or æ.", [{ written: "ven", sound: "vɛnˀ", gloss: "friend" }], {
      confusableWith: ["e"],
    }),
    vowel(
      "ø",
      "close-mid front rounded vowel",
      "Say “e” (as in “say”) with rounded lips. Like German ö.",
      [{ written: "øl", sound: "ølˀ", gloss: "beer" }],
      { spelling: "Written ø." }
    ),
    vowel("a", "open front vowel", "A bright, open “a”, close to the vowel in British “cat”.", [{ written: "han", sound: "han", gloss: "he" }], {
      confusableWith: ["ɑ"],
    }),
    vowel(
      "ɑ",
      "open back unrounded vowel",
      "Like the vowel in “father”, with the mouth wide open.",
      [{ written: "far", sound: "fɑˀ", gloss: "father" }],
      { confusableWith: ["a"] }
    ),
    vowel("u", "close back rounded vowel", "Like the vowel in “moon”, with strongly rounded lips.", [{ written: "du", sound: "duˀ", gloss: "you" }]),
    vowel("o", "close-mid back rounded vowel", "Between “moon” and “saw”, lips rounded.", [{ written: "to", sound: "toˀ", gloss: "two" }]),
    vowel(
      "ɔ",
      "open-mid back rounded vowel",
      "Close to the vowel in “thought”. Spelled å, and often o.",
      [{ written: "båd", sound: "bɔːð", gloss: "boat" }],
      { spelling: "The letter å is always this kind of sound." }
    ),
    vowel(
      "ʌ",
      "open-mid back vowel (unrounded or lightly rounded)",
      "A relaxed back vowel, a little like the vowel in “cut” said further back. Very common as the pronunciation of the letter o in short words.",
      [
        { written: "kop", sound: "kʌb", gloss: "cup" },
        { written: "for", sound: "fʌ", gloss: "for" },
      ],
      { spelling: "The letter o is not always [o]: in kop and for it is usually [ʌ] or [ɔ].", confusableWith: ["ɔ", "o"] }
    ),
    vowel("ə", "mid central vowel (schwa)", "The weak vowel in unstressed syllables, like the last sound of English “sofa”. Spelled -e.", [
      { written: "gade", sound: "ˈɡɛðə", gloss: "street" },
    ]),
    vowel(
      "ɐ",
      "near-open central vowel",
      "A lax “a”-like sound that Danish uses for unstressed -er and for r after vowels.",
      [{ written: "kopper", sound: "ˈkʌbɐ", gloss: "cups" }],
      {
        spelling: "Final -er is pronounced [ɐ], not “-er”.",
        confusableWith: ["ə"],
      }
    ),
    cons("p", "voiceless bilabial stop (aspirated)", "Like English initial “p” in “pen”, with a puff of air at the start of a stressed syllable.", [
      { written: "pose", sound: "ˈpoːsə", gloss: "bag" },
    ]),
    cons("t", "voiceless alveolar stop (aspirated)", "Like English initial “t”, with a puff of air; the tongue is a little more forward.", [
      { written: "tak", sound: "tɑk", gloss: "thanks" },
    ]),
    cons("k", "voiceless velar stop (aspirated)", "Like English initial “k”, with a puff of air.", [{ written: "kop", sound: "kʌb", gloss: "cup" }]),
    cons(
      "b",
      "unaspirated stop (b)",
      "Spelled b but made without voicing and without a puff of air, so to English ears it sounds close to “p”.",
      [{ written: "bil", sound: "biˀl", gloss: "car" }],
      {
        spelling: "Danish b, d, g are not voiced like English b, d, g.",
        confusableWith: ["p"],
      }
    ),
    cons(
      "d",
      "unaspirated stop (d)",
      "Spelled d at the start of a syllable: no voicing, no puff of air; close to a soft “t”.",
      [{ written: "dag", sound: "dæˀ", gloss: "day" }],
      { confusableWith: ["t", "ð"] }
    ),
    cons(
      "g",
      "unaspirated stop (g)",
      "Spelled g at the start of a syllable: no voicing, close to a soft “k”.",
      [{ written: "gade", sound: "ˈɡɛðə", gloss: "street" }],
      { confusableWith: ["k"] }
    ),
    cons(
      "ð",
      "“soft d” (dental approximant)",
      "The famous Danish soft d, spelled d after a vowel. A relaxed “th” as in “the”, with the tongue barely touching the teeth.",
      [
        { written: "mad", sound: "mæð", gloss: "food" },
        { written: "rød", sound: "ʁœð", gloss: "red" },
      ],
      { spelling: "Spelled d after a vowel (and in -ed endings).", confusableWith: ["d"] }
    ),
    cons(
      "w",
      "labial-velar glide",
      "A short “w”/“u” glide at the end of a syllable, like the end of English “cow”. It appears in words such as hav and in tog and af.",
      [{ written: "hav", sound: "hɑwˀ", gloss: "sea" }],
      { confusableWith: ["v", "u"] }
    ),
    cons("f", "voiceless labiodental fricative", "As in English “fish”.", [{ written: "fisk", sound: "fesk", gloss: "fish" }]),
    cons("v", "labiodental approximant", "Softer than English “v”, almost like a “w” with the lower lip near the teeth.", [
      { written: "vand", sound: "vanˀ", gloss: "water" },
    ]),
    cons("s", "voiceless alveolar fricative", "As in English “sun”.", [{ written: "sol", sound: "soˀl", gloss: "sun" }]),
    cons("h", "glottal fricative", "As in English “hat”.", [{ written: "hus", sound: "huˀs", gloss: "house" }]),
    cons("j", "palatal approximant", "Like English “y” in “yes”.", [{ written: "ja", sound: "jɛ", gloss: "yes" }], {
      spelling: "Also the g/j in endings like -ig and in jeg.",
    }),
    cons("l", "alveolar lateral", "A clear l, close to English “light”.", [{ written: "lys", sound: "lyˀs", gloss: "light" }]),
    cons("m", "bilabial nasal", "As in English “man”.", [{ written: "mor", sound: "moɐˀ", gloss: "mother" }]),
    cons("n", "alveolar nasal", "As in English “no”.", [{ written: "nu", sound: "nu", gloss: "now" }]),
    cons("ŋ", "velar nasal", "The ng of English “sing”. Spelled ng or nk.", [{ written: "lang", sound: "lɑŋˀ", gloss: "long" }]),
    cons(
      "ʁ",
      "uvular approximant",
      "Danish r is made at the back of the throat, a little like a gentle gargle or French r. After vowels it turns into an a-like [ɐ].",
      [
        { written: "rød", sound: "ʁœð", gloss: "red" },
        { written: "mor", sound: "moɐˀ", gloss: "mother" },
      ],
      {
        confusableWith: ["r"],
      }
    ),
    {
      symbol: "ˀ",
      kind: "prosody",
      name: "stød (glottal catch)",
      how: "A very short creaky catch in the voice on a long vowel or a vowel plus nasal. It can distinguish words.",
      keywords: [
        { written: "hund", sound: "hunˀ", gloss: "dog" },
        { written: "hun", sound: "hun", gloss: "she" },
        { written: "mand", sound: "manˀ", gloss: "man" },
        { written: "man", sound: "man", gloss: "one (people in general)" },
      ],
      spelling: "Stød is not written. You learn it with each word.",
    },
    {
      symbol: "ː",
      kind: "prosody",
      name: "long vowel",
      how: "The vowel is held about twice as long. Length matters in Danish, but it is optional in this game.",
      keywords: [{ written: "pose", sound: "ˈpoːsə", gloss: "bag" }],
    },
  ],
  meanings: MEANING_LIBRARY,
  lexicon: [
    {
      id: "vand",
      written: "vand",
      sound: "vanˀ",
      alsoAccept: ["van", "vɑn"],
      meaning: "water",
      pos: "noun",
      note: "Has stød (the creaky catch). A neuter noun: “the water” is vandet.",
      verified: false,
    },
    {
      id: "kop",
      written: "kop",
      sound: "kʌb",
      alsoAccept: ["kɔb", "kʌp", "kɔp"],
      meaning: "cup",
      pos: "noun",
      note: "Most nouns form the plural with -er: kop → kopper.",
      verified: false,
    },
    {
      id: "kopper",
      written: "kopper",
      sound: "ˈkʌbɐ",
      alsoAccept: ["ˈkɔbɐ", "ˈkʌpɐ", "ˈkɔbər"],
      meaning: "cups",
      pos: "noun",
      note: "kop + -er = more than one cup. The final -er is pronounced [ɐ].",
      verified: false,
    },
    {
      id: "jeg",
      written: "jeg",
      sound: "jɑɪ",
      alsoAccept: ["jaj", "jɑj", "jɑi"],
      meaning: "i",
      pos: "pron",
      note: "“I”. The final g is not pronounced as a separate hard consonant.",
      verified: false,
    },
    {
      id: "har",
      written: "har",
      sound: "hɑˀ",
      alsoAccept: ["hɑ", "ha", "haː", "hɑː"],
      meaning: "have",
      pos: "verb",
      note: "Danish verbs do not change with the person: jeg har, du har, han har.",
      verified: false,
    },
    {
      id: "ikke",
      written: "ikke",
      sound: "ˈeɡə",
      alsoAccept: ["ˈɛɡə", "ˈeɡ̊ə", "ˈeɡe"],
      meaning: "not",
      pos: "adv",
      note: "Normally comes right after the verb: jeg har ikke … Spelled with i but often said with an e-like vowel.",
      verified: false,
    },
    {
      id: "nøgle",
      written: "nøgle",
      sound: "ˈnɔjlə",
      alsoAccept: ["ˈnʌjlə", "ˈnɔjlɐ", "ˈnøjlə"],
      meaning: "key",
      pos: "noun",
      note: "An en-word: en nøgle (the key: nøglen).",
      verified: false,
    },
    {
      id: "en",
      written: "en",
      sound: "en",
      alsoAccept: ["eˀn", "ɛn"],
      meaning: "a",
      pos: "det",
      note: "“a/an” for common-gender nouns (en nøgle, en kop). Neuter nouns use et.",
      verified: false,
    },
    {
      id: "port",
      written: "port",
      sound: "ˈpɒɐd",
      alsoAccept: ["pɔɐd", "poɐd", "pɒɐt", "ˈpɒɐ̯d"],
      meaning: "gate",
      pos: "noun",
      note: "An en-word: en port. Add -en for “the”: porten.",
      verified: false,
    },
    {
      id: "porten",
      written: "porten",
      sound: "ˈpɒɐdn",
      alsoAccept: ["ˈpɔɐdn", "ˈpɒɐdən", "ˈpoɐdn"],
      meaning: "gate",
      pos: "noun",
      note: "port + -en: the definite article is a suffix in Danish.",
      verified: false,
    },
    {
      id: "lukket",
      written: "lukket",
      sound: "ˈlɔɡəð",
      alsoAccept: ["ˈlɔɡəd", "ˈlɔkəð", "ˈlʌɡəð", "ˈlɔkəd"],
      meaning: "closed",
      pos: "adj",
      note: "From the verb lukke (to close); the -et ending is said [əð].",
      verified: false,
    },
    {
      id: "fordi",
      written: "fordi",
      sound: "fʌˈdi",
      alsoAccept: ["fɔˈdi", "foˈdi", "fɒˈdi"],
      meaning: "because",
      pos: "conj",
      note: "Introduces the reason: … fordi porten er lukket.",
      verified: false,
    },
    {
      id: "brug",
      written: "brug",
      sound: "bʁuˀ",
      alsoAccept: ["bʁu", "bru", "bʁuː"],
      meaning: "need",
      pos: "noun",
      note: "“Have brug for” literally means “have use for”: that is how Danish says “need”.",
      verified: false,
    },
    {
      id: "for",
      written: "for",
      sound: "fʌ",
      alsoAccept: ["fɔ", "fɒ", "fo", "fɔɐ"],
      meaning: "for",
      pos: "prep",
      note: "Here part of the fixed phrase “have brug for” (to need).",
      verified: false,
    },
    {
      id: "er",
      written: "er",
      sound: "ɛɐ",
      alsoAccept: ["æɐ", "eɐ", "ɛɑ"],
      meaning: "is",
      pos: "verb",
      note: "“is / am / are”: the same form for every person: jeg er, du er, porten er.",
      verified: false,
    },
  ],
  encounters: [
    {
      id: "fountain",
      name: "Quay Water Pump",
      phase: "Observe",
      position: SPOTS.fountain.position,
      approach: SPOTS.fountain.approach,
      scene: "At the Nyhavn quay a brass pump drips into a stone basin. A child fills a cup, drinks, and says one word as they point at the stream.",
      say: ["Vand."],
      clues: [
        {
          id: "f-pump",
          kind: "object",
          text: "A brass pump spouts a thin stream into the stone basin.",
          picture: "pump",
          supports: ["water"],
          about: ["vand"],
        },
        {
          id: "f-drink",
          kind: "action",
          text: "The child holds a cup under the spout, then drinks from it.",
          picture: "drink",
          supports: ["water", "drink", "cup"],
          about: ["vand"],
        },
        {
          id: "f-point",
          kind: "gesture",
          text: "Pointing at the stream, the child says the word again, slowly.",
          picture: "point",
          supports: ["water"],
          about: ["vand"],
        },
        {
          id: "f-sign",
          kind: "writing",
          text: "The same written word is painted on the pump, on the basin and on a bucket.",
          picture: "writing",
          supports: ["water", "drink"],
          about: ["vand"],
        },
        { id: "f-bird", kind: "context", text: "A seagull lands on the basin rim and is shooed away.", picture: "bird", supports: [] },
      ],
      drills: ["vand"],
      reveal: {
        line: "The pump, the basin and the bucket all carry the same word.",
        discovery: "“vand” is written wherever people draw or drink water. The child’s cup and the pointing agree.",
      },
    },
    {
      id: "vendor",
      name: "Coffee Kiosk",
      phase: "Connect",
      position: SPOTS.vendor.position,
      approach: SPOTS.vendor.approach,
      requires: "fountain",
      scene:
        "At a red kiosk on the quay the vendor lifts one steaming cup and names it, then sweeps her hand over a tray of cups and names them again with a small change.",
      say: ["En kop.", "Kopper."],
      clues: [
        {
          id: "v-one",
          kind: "contrast",
          text: "One cup is lifted and named. Then a whole tray is indicated and the word ends differently.",
          picture: "cups",
          supports: ["cup", "cups"],
          about: ["kop", "kopper"],
        },
        {
          id: "v-count",
          kind: "gesture",
          text: "She counts on her fingers: one, then she opens her whole hand over the tray.",
          picture: "count",
          supports: ["cups", "a"],
          about: ["kopper", "en"],
        },
        {
          id: "v-steam",
          kind: "object",
          text: "Steam rises from the cup: it holds something hot to drink.",
          picture: "steam",
          supports: ["cup", "drink"],
          about: ["kop"],
        },
        { id: "v-tray", kind: "object", text: "The tray holds a row of identical cups.", picture: "tray", supports: ["cups"], about: ["kopper"] },
        { id: "v-bell", kind: "context", text: "A bicycle bell rings behind the queue.", picture: "bell", supports: [] },
      ],
      drills: ["kop", "kopper"],
      exposure: ["en"],
      reveal: {
        line: "One cup and many cups sound almost the same: the second just ends differently.",
        discovery: "The two words share a root; the extra ending appears when there are several. A noun can change at its end.",
      },
    },
    {
      id: "guard",
      name: "Harbour Master",
      phase: "Hear",
      position: SPOTS.guard.position,
      approach: SPOTS.guard.approach,
      requires: "vendor",
      scene:
        "The harbour master raises a brass key and speaks. Then he turns to an empty-handed traveller and speaks the same sentence again, with one extra word.",
      say: ["Jeg har en nøgle.", "Jeg har ikke en nøgle."],
      clues: [
        { id: "g-chest", kind: "gesture", text: "He taps his own chest as he starts to speak.", picture: "chest", supports: ["i"], about: ["jeg"] },
        {
          id: "g-turn",
          kind: "action",
          text: "The traveller, asked a question, answers by touching his own chest and beginning with the same first word.",
          picture: "chest",
          supports: ["i", "you"],
          about: ["jeg"],
        },
        {
          id: "g-key",
          kind: "object",
          text: "He holds up a brass key and the word that follows is said clearly.",
          picture: "key",
          supports: ["key"],
          about: ["nøgle"],
        },
        { id: "g-hold", kind: "action", text: "His hand closes around the key. He keeps it.", picture: "have", supports: ["have"], about: ["har"] },
        {
          id: "g-belt",
          kind: "gesture",
          text: "He hangs the key on his belt, pats it, and repeats the middle word.",
          picture: "hands",
          supports: ["have", "want"],
          about: ["har"],
        },
        {
          id: "g-empty",
          kind: "contrast",
          text: "To the empty-handed traveller he repeats the sentence with one extra word, and the traveller shrugs.",
          picture: "shrug",
          supports: ["not", "nothave"],
          about: ["ikke"],
        },
        {
          id: "g-shake",
          kind: "gesture",
          text: "He shakes his head slightly as he says the longer sentence.",
          picture: "shrug",
          supports: ["not", "nothave"],
          about: ["ikke"],
        },
        {
          id: "g-writing",
          kind: "writing",
          text: "A sign on the harbour office shows the word for the key beside a drawing of one.",
          picture: "writing",
          supports: ["key"],
          about: ["nøgle"],
        },
        { id: "g-dog", kind: "context", text: "A seagull perches on a bollard behind him.", picture: "bird", supports: [] },
      ],
      drills: ["jeg", "har", "ikke", "nøgle"],
      reveal: {
        line: "The same sentence for the man with a key and the man without, with one word more.",
        discovery: "Self, possession and object line up in that order; the extra small word reverses the claim.",
      },
    },
    {
      id: "gate",
      name: "Harbour Gate",
      phase: "Compose",
      position: SPOTS.gate.position,
      approach: SPOTS.gate.approach,
      requires: "guard",
      scene:
        "The iron harbour gate hangs shut with a padlock and a lettered tag. The harbour master pulls at it, then points at his key and at the gate, palm up, and gives a reason in one long sentence.",
      say: ["Porten er lukket.", "Jeg har brug for en nøgle, fordi porten er lukket."],
      clues: [
        {
          id: "k-gate",
          kind: "object",
          text: "A heavy iron gate. A padlock holds it shut.",
          picture: "gate",
          supports: ["gate", "closed"],
          about: ["port", "lukket"],
        },
        {
          id: "k-sign",
          kind: "writing",
          text: "The word on the board above the gate is the one he used for the gate itself.",
          picture: "writing",
          supports: ["gate"],
          about: ["port"],
        },
        {
          id: "k-pull",
          kind: "action",
          text: "He pulls the gate. It does not move. He says one word about it.",
          picture: "pull",
          supports: ["closed"],
          about: ["lukket"],
        },
        {
          id: "k-tag",
          kind: "writing",
          text: "The tag on the padlock carries the same word he used for the gate’s state.",
          picture: "padlock",
          supports: ["closed"],
          about: ["lukket"],
        },
        {
          id: "k-need",
          kind: "gesture",
          text: "He points at the key, then at the gate, open palm up, reaching.",
          picture: "need",
          supports: ["need", "want"],
          about: ["brug"],
        },
        {
          id: "k-because",
          kind: "contrast",
          text: "His sentence is in two halves, joined by one short word while he moves his hand from the key to the gate.",
          picture: "because",
          supports: ["because"],
          about: ["fordi"],
        },
        {
          id: "k-why",
          kind: "context",
          text: "When he stops after the first half, the traveller raises his eyebrows as if to ask “why?”. He adds the second half, beginning with the linking word.",
          picture: "speak",
          supports: ["because"],
          about: ["fordi"],
        },
        { id: "k-bike", kind: "context", text: "A cyclist rings a bell and rolls past.", picture: "bicycle", supports: [] },
      ],
      drills: ["port", "lukket", "fordi"],
      exposure: ["er", "brug", "for", "en", "porten"],
      reveal: {
        line: "The gate stays shut, and he explains why he is holding the key.",
        discovery: "A reason comes after a short linking word: first what he needs, then why. The gate’s state is a describing word.",
      },
    },
    {
      id: "archive",
      name: "Archive Door",
      phase: "Speak",
      position: SPOTS.archive.position,
      approach: SPOTS.archive.approach,
      requires: "gate",
      scene:
        "The archivist waits at the door with her arms folded. She does not translate anything. She wants to hear you say what the harbour master said.",
      say: [],
      clues: [
        { id: "a-wait", kind: "context", text: "She nods slowly each time you get a word right, and says nothing.", picture: "ear", supports: [] },
      ],
      drills: [],
      reveal: {
        line: "The archivist nods and opens the door.",
        discovery: "You can now build and say a whole sentence from the words you recorded.",
      },
    },
  ],
  finale: {
    encounter: "archive",
    prompt: "Tell the archivist what the harbour master told you: he needs a key because the gate is closed.",
    target: ["jeg", "har", "brug", "for", "en", "nøgle", "fordi", "porten", "er", "lukket"],
    shuffled: ["porten", "nøgle", "jeg", "lukket", "har", "fordi", "en", "brug", "er", "for"],
    translation: "I need a key because the gate is closed.",
    successLine: "The archivist smiles and opens the door: “Jeg har brug for en nøgle, fordi porten er lukket.”",
  },
  ui: {
    ink: "#1f2c3d",
    inkSoft: "#2c3e55",
    paper: "#f5eedc",
    paperDeep: "#e7dbbd",
    accent: "#c8102e",
    accentText: "#fff7e8",
    gold: "#e8b923",
    good: "#2f7d5c",
    muted: "#6b7a8c",
    wash: "rgba(200,16,46,.14)",
    halftone: "rgba(31,44,61,.9)",
  },
  world: {
    scenery: "nyhavn",
    // Three floating terraces joined by stairs (see packs/layout.ts), in pastel versions of the Nyhavn colours.
    ...terraces({ a: ["#efe2cf", "#dcc6b4"], b: ["#f2d9c6", "#d9b8a8"], d: ["#ecd3d0", "#cfa9a6"], stairs: "#f8eee2" }),
    palette: {
      ground: "#efe2cf",
      street: "#e6d5bd",
      plaza: "#f7efe0",
      water: "#a6d0df",
      sky: ["#b9d9ea", "#e9f1ee"],
      fog: "#dcecef",
      ink: "#6f86a6",
      cloaks: ["#e8828a", "#7f9cc4", "#e8c36a", "#8cc4b4", "#b79bc9"],
      accent: "#df6670",
      light: { ambient: "#fff4ee", hemiSky: "#ffffff", hemiGround: "#cddcf0", sun: "#fffaf0" },
    },
    buildings: [...westHouses(FACADE, ROOFS), archiveHouse("#f4ead2", "#b58e86"), gateWall("#d9cbb6", "#bfae96")],
    npcs: [
      { ...NPC_SPOTS.child, color: "#e8828a", tool: "cup" },
      { ...NPC_SPOTS.vendor, color: "#8cc4b4", tool: "cup" },
      { ...NPC_SPOTS.guard, color: "#7f9cc4", tool: "key" },
      { ...NPC_SPOTS.traveller, color: "#b79bc9" },
      { ...NPC_SPOTS.archivist, color: "#e8c36a" },
    ],
    signs: [
      { words: ["vand"], position: [0, 0.34, 3.97], width: 1.1 },
      { words: ["kop"], position: [-7.6, 0.62, 0.2], width: 0.9 },
      { words: ["lukket"], position: [0, 4.9, -15.2], width: 1.5 },
      { text: "Nyhavn", position: [-4.4, 5.6, -15.32], width: 1.7 },
      { text: "Arkivet", position: [-9.33, 4.7, -7.4], rotationY: Math.PI / 2, width: 1.5 },
    ],
  },
  verification: {
    status: "unverified",
    note: "Spellings, meanings and grammar notes are standard Danish. All IPA transcriptions and phoneme descriptions are unchecked: please compare them with Den Danske Ordbog (ordnet.dk) or a native speaker before relying on them.",
  },
  sources: ["Standard Danish orthography (Retskrivningsordbogen)", "Den Danske Ordbog, ordnet.dk (to verify pronunciations against)"],
};
