import { MEANING_LIBRARY } from "../maruPictureData";
import type { LanguagePack, PhonemeEntry } from "./types";

/**
 * Maru: an invented language set in a sunlit-sandstone Copenhagen, for deciphering from scratch.
 * Everything here is original and fully specified, so its romanisation (`sound`) is authoritative.
 * No human voice speaks Maru: the Danish voice reads the romanisation as syllables.
 */

const v = (symbol: string, how: string, keywords: PhonemeEntry["keywords"]): PhonemeEntry => ({
  symbol,
  kind: "vowel",
  name: "vowel",
  how,
  keywords,
});
const c = (symbol: string, how: string, keywords: PhonemeEntry["keywords"]): PhonemeEntry => ({
  symbol,
  kind: "consonant",
  name: "consonant",
  how,
  keywords,
});

export const maru: LanguagePack = {
  id: "maru",
  name: "Maru (invented)",
  nativeName: "Maru",
  city: "Copenhagen",
  district: "Højbro Plads",
  script: "glyph",
  speech: { synth: "da-DK", recog: "da-DK", rate: 0.7 },
  notation: {
    kind: "romanisation",
    label: "Maru spelling",
    help: "Write the sounds you hear with the letters of Maru: a e i o u and p t k m n s v l r g.",
    keyboard: ["a", "e", "i", "o", "u", "p", "t", "k", "m", "n", "s", "v", "l", "r", "g"],
    ignore: " -.,",
  },
  phonology: [
    v("a", "Open, like “a” in “father”. Always the same sound.", [
      { written: "sua", sound: "sua", gloss: "water" },
      { written: "ta", sound: "ta", gloss: "because" },
    ]),
    v("e", "Like “e” in “bed”.", [{ written: "eno", sound: "eno", gloss: "have" }]),
    v("i", "Like “ee” in “see”, short.", [
      { written: "mi", sound: "mi", gloss: "I" },
      { written: "kiru", sound: "kiru", gloss: "key" },
    ]),
    v("o", "Like “o” in “more”, without a glide.", [
      { written: "kopo", sound: "kopo", gloss: "cup" },
      { written: "ganu", sound: "ganu", gloss: "gate" },
    ]),
    v("u", "Like “oo” in “moon”, short.", [
      { written: "sua", sound: "sua", gloss: "water" },
      { written: "kiru", sound: "kiru", gloss: "key" },
    ]),
    c("p", "Soft “p”, as in “spin”.", [
      { written: "kopo", sound: "kopo", gloss: "cup" },
      { written: "sapo", sound: "sapo", gloss: "closed" },
    ]),
    c("k", "Soft “k”, as in “skip”.", [
      { written: "kopo", sound: "kopo", gloss: "cup" },
      { written: "kiru", sound: "kiru", gloss: "key" },
    ]),
    c("s", "As in “sun”.", [
      { written: "sua", sound: "sua", gloss: "water" },
      { written: "sapo", sound: "sapo", gloss: "closed" },
    ]),
    c("m", "As in “man”.", [{ written: "mi", sound: "mi", gloss: "I" }]),
    c("n", "As in “no”.", [
      { written: "ganu", sound: "ganu", gloss: "gate" },
      { written: "eno", sound: "eno", gloss: "have" },
    ]),
    c("g", "Always hard, as in “go”.", [{ written: "ganu", sound: "ganu", gloss: "gate" }]),
    c("r", "A quick tap of the tongue, as in Spanish “pero”.", [{ written: "kiru", sound: "kiru", gloss: "key" }]),
    c("t", "Soft “t”, as in “stop”.", [{ written: "ta", sound: "ta", gloss: "because" }]),
  ],
  meanings: MEANING_LIBRARY,
  lexicon: [
    { id: "sua", written: "sua", sound: "sua", meaning: "water", pos: "noun", verified: true },
    { id: "kopo", written: "kopo", sound: "kopo", meaning: "cup", pos: "noun", verified: true },
    {
      id: "koponi",
      written: "koponi",
      sound: "koponi",
      meaning: "cups",
      pos: "noun",
      note: "kopo + -ni: the suffix -ni marks more than one.",
      verified: true,
    },
    { id: "mi", written: "mi", sound: "mi", meaning: "i", pos: "pron", verified: true },
    { id: "eno", written: "eno", sound: "eno", meaning: "have", pos: "verb", verified: true },
    {
      id: "naeno",
      written: "naeno",
      sound: "naeno",
      meaning: "nothave",
      pos: "verb",
      note: "na- + eno: the prefix na- reverses a verb.",
      verified: true,
    },
    { id: "kiru", written: "kiru", sound: "kiru", meaning: "key", pos: "noun", verified: true },
    {
      id: "ta",
      written: "ta",
      sound: "ta",
      meaning: "because",
      pos: "conj",
      note: "Splits a sentence into the claim and its reason.",
      verified: true,
    },
    { id: "ganu", written: "ganu", sound: "ganu", meaning: "gate", pos: "noun", verified: true },
    { id: "sapo", written: "sapo", sound: "sapo", meaning: "closed", pos: "adj", verified: true },
  ],
  encounters: [
    {
      id: "fountain",
      name: "Højbro Fountain",
      phase: "Observe",
      position: [0, 0, 2],
      approach: [0, 4.6],
      scene:
        "At Højbro Plads a child fills a cup. The same carved mark is on the fountain rim, on every cup and on a public spout. As the child drinks, they say one word.",
      say: ["sua"],
      clues: [
        {
          id: "m-f-drink",
          kind: "action",
          text: "The child holds a cup under the spout and drinks.",
          picture: "drink",
          supports: ["water", "drink", "cup"],
          about: ["sua"],
        },
        {
          id: "m-f-spout",
          kind: "object",
          text: "A public spout runs into the fountain basin.",
          picture: "pump",
          supports: ["water"],
          about: ["sua"],
        },
        {
          id: "m-f-mark",
          kind: "writing",
          text: "The same carved mark is on the rim, on every cup and on the spout.",
          picture: "writing",
          supports: ["water", "drink"],
          about: ["sua"],
        },
        {
          id: "m-f-point",
          kind: "gesture",
          text: "The child points at the stream and says the word again.",
          picture: "point",
          supports: ["water"],
          about: ["sua"],
        },
        { id: "m-f-bird", kind: "context", text: "A pigeon bathes at the basin edge.", picture: "bird", supports: [] },
      ],
      drills: ["sua"],
      reveal: { line: "The same mark is on the rim, on every cup and on the spout.", discovery: "The mark recurs wherever people drink." },
    },
    {
      id: "vendor",
      name: "Gammel Strand Market",
      phase: "Connect",
      position: [-6, 0, -2],
      approach: [-4.1, -0.6],
      requires: "fountain",
      scene: "At the canal market Nera points to one cup and says a word, then points to a whole tray of cups and says a related word.",
      say: ["kopo", "koponi"],
      clues: [
        {
          id: "m-v-contrast",
          kind: "contrast",
          text: "One cup is named, then a tray: the second word has something extra at the end.",
          picture: "cups",
          supports: ["cup", "cups"],
          about: ["kopo", "koponi"],
        },
        {
          id: "m-v-count",
          kind: "gesture",
          text: "Nera counts one finger, then opens her whole hand over the tray.",
          picture: "count",
          supports: ["cups"],
          about: ["koponi"],
        },
        { id: "m-v-tray", kind: "object", text: "The tray holds a row of identical cups.", picture: "tray", supports: ["cups"], about: ["koponi"] },
        { id: "m-v-steam", kind: "object", text: "Steam rises from the single cup.", picture: "steam", supports: ["cup", "drink"], about: ["kopo"] },
        { id: "m-v-bell", kind: "context", text: "A bell rings on a passing barge.", picture: "bell", supports: [] },
      ],
      drills: ["kopo", "koponi"],
      reveal: {
        line: "You hear a stable root and an added ending when there are several cups.",
        discovery: "The two words share a root; the ending marks more than one.",
      },
    },
    {
      id: "guard",
      name: "Christiansborg Guard",
      phase: "Hear",
      position: [0, 0, -7],
      approach: [0, -4.8],
      requires: "vendor",
      scene: "The guard raises a key and speaks. Then he turns to an empty-handed traveller and speaks again, with one small difference.",
      say: ["mi eno kiru", "mi naeno kiru"],
      clues: [
        { id: "m-g-chest", kind: "gesture", text: "He taps his own chest as he begins.", picture: "chest", supports: ["i"], about: ["mi"] },
        {
          id: "m-g-turn",
          kind: "action",
          text: "The traveller, asked a question, touches his own chest and begins with the same first sound.",
          picture: "chest",
          supports: ["i", "you"],
          about: ["mi"],
        },
        { id: "m-g-key", kind: "object", text: "He holds up a key as he says the last word.", picture: "key", supports: ["key"], about: ["kiru"] },
        {
          id: "m-g-carving",
          kind: "writing",
          text: "A key is carved over the guard post, beside the mark for his last word.",
          picture: "writing",
          supports: ["key"],
          about: ["kiru"],
        },
        { id: "m-g-hold", kind: "action", text: "His hand closes around the key.", picture: "have", supports: ["have"], about: ["eno"] },
        {
          id: "m-g-belt",
          kind: "gesture",
          text: "He hangs the key on his belt, pats it and repeats the middle word.",
          picture: "hands",
          supports: ["have", "want"],
          about: ["eno"],
        },
        {
          id: "m-g-empty",
          kind: "contrast",
          text: "To the empty-handed traveller he says it again with a small prefix, and the traveller shrugs.",
          picture: "shrug",
          supports: ["not", "nothave"],
          about: ["naeno"],
        },
        {
          id: "m-g-shake",
          kind: "gesture",
          text: "He shakes his head slightly as he says the second sentence.",
          picture: "shrug",
          supports: ["not", "nothave"],
          about: ["naeno"],
        },
        { id: "m-g-bird", kind: "context", text: "A gull cries overhead.", picture: "bird", supports: [] },
      ],
      drills: ["mi", "eno", "kiru", "naeno"],
      reveal: {
        line: "Gesture, sound and writing align: person, possession, key.",
        discovery: "The prefix reverses the claim: with it, the traveller has no key.",
      },
    },
    {
      id: "gate",
      name: "Slotsholmen Gate",
      phase: "Compose",
      position: [0, 0, -13],
      approach: [0, -11.1],
      requires: "guard",
      scene:
        "The barred Slotsholmen gate bears two carved marks. The guard points at them and finishes his sentence with a short linking word and the sound of the marks.",
      say: ["mi eno kiru ta ganu sapo"],
      clues: [
        {
          id: "m-k-gate",
          kind: "object",
          text: "A barred gate with two carved marks above it.",
          picture: "gate",
          supports: ["gate", "closed"],
          about: ["ganu", "sapo"],
        },
        { id: "m-k-pull", kind: "action", text: "He pulls the bars: nothing moves.", picture: "pull", supports: ["closed"], about: ["sapo"] },
        {
          id: "m-k-because",
          kind: "contrast",
          text: "His sentence has two halves, joined by one short word as his hand moves from key to gate.",
          picture: "because",
          supports: ["because"],
          about: ["ta"],
        },
        {
          id: "m-k-why",
          kind: "context",
          text: "When he stops after the first half, the traveller raises his eyebrows as if asking “why?”. He adds the second half, beginning with the linking word.",
          picture: "speak",
          supports: ["because"],
          about: ["ta"],
        },
        {
          id: "m-k-writing",
          kind: "writing",
          text: "The two carved marks match the last two sounds he made.",
          picture: "writing",
          supports: ["gate", "closed"],
          about: ["ganu", "sapo"],
        },
        { id: "m-k-cart", kind: "context", text: "A cart rattles by in the distance.", picture: "wheel", supports: [] },
      ],
      drills: ["ta", "ganu", "sapo"],
      reveal: { line: "The gate stays shut. The guard gives a reason.", discovery: "A linking word turns two clauses into claim and reason." },
    },
    {
      id: "archive",
      name: "Royal Archive Door",
      phase: "Speak",
      position: [8, 0, -7],
      approach: [7.7, -7],
      requires: "gate",
      scene: "The archivist waits without translating. They need to know whether you understood the guard.",
      say: [],
      clues: [{ id: "m-a-wait", kind: "context", text: "They nod slowly at each word you get right.", picture: "ear", supports: [] }],
      drills: [],
      reveal: {
        line: "The archivist nods and opens the door.",
        discovery: "You can now build and say a whole sentence from the words you recorded.",
      },
    },
  ],
  finale: {
    encounter: "archive",
    prompt: "Tell the archivist what the guard told you: he needs the key because the gate is closed.",
    target: ["mi", "eno", "kiru", "ta", "ganu", "sapo"],
    shuffled: ["ganu", "kiru", "mi", "sapo", "eno", "ta"],
    translation: "I have the key, because the gate is closed.",
    successLine: "The archivist nods and opens the door: “mi eno kiru ta ganu sapo”.",
  },
  ui: {
    ink: "#3a1626",
    inkSoft: "#2a1520",
    paper: "#f6e8c8",
    paperDeep: "#ecd9ad",
    accent: "#b3263f",
    accentText: "#fff3d6",
    gold: "#f2c744",
    good: "#2f8f6b",
    muted: "#8a6a60",
    wash: "rgba(214,44,84,.38)",
    halftone: "rgba(74,22,38,.9)",
  },
  world: {
    scenery: "sandstone",
    palette: {
      ground: "#f3cf63",
      street: "#eaa94a",
      plaza: "#f9e393",
      water: "#45bdb2",
      fog: "#f6c27f",
      ink: "#4a1626",
      cloaks: ["#c8452e", "#2f6f8f", "#8a1c33", "#6b4a7a", "#2a5f56"],
      accent: "#b33a4a",
      light: { ambient: "#ffd6a0", hemiSky: "#fff0b8", hemiGround: "#d8506a", sun: "#fff4d0" },
    },
    buildings: [
      { position: [-10, 0, 6], size: [5.4, 4.6, 4.5], color: "#f1bd4a", roof: "#b33a4a", faces: ["e", "s"] },
      { position: [9, 0, 6], size: [5.7, 5.2, 4.8], color: "#f6d56f", roof: "#b33a4a", faces: ["w", "s"] },
      { position: [-10, 0, -4], size: [4.8, 5.4, 5.8], color: "#e9a23f", roof: "#7c2a3e", faces: ["e", "s"] },
      { position: [10.7, 0, -2], size: [4.6, 5.8, 6.5], color: "#f3c552", roof: "#7c2a3e", faces: ["w", "s"] },
      { position: [-8.5, 0, -12], size: [6.2, 5.6, 4.5], color: "#f8dd84", roof: "#b33a4a", faces: ["e", "s"] },
      { position: [9, 0, -11], size: [5.5, 5.6, 4.5], color: "#e8a548", roof: "#7c2a3e", faces: ["w", "s"] },
      { position: [10.6, 0, -7], size: [3, 5, 3.2], color: "#f9e29a", roof: "#7c2a3e", faces: ["w"] },
      { position: [0, 0, -14.4], size: [10, 6.4, 1.4], color: "#e6a43c", roof: "#7c2a3e", faces: ["s"], kind: "wall" },
    ],
    npcs: [
      { position: [1.4, 0, 3.1], color: "#c8452e", scale: 0.7, facing: -0.6, tool: "cup" },
      { position: [-6, 0, -3.15], color: "#2f6f8f", facing: 0, tool: "cup" },
      { position: [0, 0, -6.7], color: "#8a1c33", scale: 1.12, facing: 0, tool: "key" },
      { position: [-1.9, 0, -5.7], color: "#6b4a7a", facing: 0.9 },
      { position: [8.2, 0, -7], color: "#2a5f56", facing: -Math.PI / 2 },
    ],
    signs: [
      { words: ["sua"], position: [0, 0.34, 1.97], width: 1.1 },
      { words: ["sua"], position: [-7.28, 2.6, 6], rotationY: Math.PI / 2, width: 1.8 },
      { words: ["mi", "eno", "kiru"], position: [8.28, 3.2, 3.2], rotationY: -Math.PI / 2, width: 1.5 },
      { words: ["kopo"], position: [-6, 0.5, -1.42], width: 0.9 },
      { words: ["ganu", "sapo"], position: [0, 5.0, -13.52], width: 1.5 },
      { words: ["kiru"], position: [9.06, 4.0, -7], rotationY: -Math.PI / 2, width: 1.2 },
    ],
  },
  verification: {
    status: "verified",
    note: "Invented language: its spelling, meanings and grammar are defined by this file and are authoritative. No real speaker exists, so the Danish voice is only an approximation of how it would sound.",
  },
  sources: ["Original conlang created for this game (src/components/tools/lingua/language.ts for the glyph shapes)"],
};
