// Generates crystal-clear neural Danish audio files for Language Quest using edge-tts.
// Usage: node scripts/generate-audio.mjs
import { buildSync } from "esbuild";
import { execSync } from "node:child_process";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

// 1. Bundle and extract all Danish phrases
const bundleDir = "/tmp/da-audio-extract";
mkdirSync(bundleDir, { recursive: true });
const bundleFile = join(bundleDir, "extract.mjs");

buildSync({
  stdin: {
    contents: `import { da } from "./src/components/tools/lingua/packs/da";
      const phrases = new Set();
      if (da.speech.testPhrase) phrases.add(da.speech.testPhrase);
      da.encounters.forEach(e => {
        if (e.spoken) phrases.add(e.spoken);
        if (e.say) e.say.forEach(s => phrases.add(s));
        e.drills.forEach(d => phrases.add(d));
      });
      da.lexicon.forEach(l => {
        phrases.add(l.written);
      });
      da.phonology?.forEach(ph => {
        ph.keywords?.forEach(k => phrases.add(k.written));
      });
      // also include common sentence combinations
      phrases.add("Jeg har en nøgle");
      phrases.add("Jeg har ikke en nøgle");
      phrases.add("Porten er lukket");
      phrases.add("Jeg har brug for en nøgle, fordi porten er lukket");
      phrases.add("Jeg har brug for en nøgle fordi porten er lukket");
      export const phraseList = Array.from(phrases);
    `,
    resolveDir: process.cwd(),
    loader: "ts",
  },
  bundle: true,
  platform: "node",
  format: "esm",
  outfile: bundleFile,
  logLevel: "error",
});

const { phraseList: out } = await import(bundleFile);

// Helper to make a URL-friendly, safe filename slug with Danish transliteration
export function slugify(text) {
  return text
    .toLowerCase()
    .replace(/æ/g, "ae")
    .replace(/ø/g, "oe")
    .replace(/å/g, "aa")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "") // strip other diacritics
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

const outDir = join(process.cwd(), "public/audio/da");
mkdirSync(outDir, { recursive: true });

const manifest = {};
const uvx = existsSync("/Users/micti/.local/bin/uvx") ? "/Users/micti/.local/bin/uvx" : "uvx";

console.log(`Generating native neural audio for ${out.length} Danish phrases...`);

for (const phrase of out) {
  const clean = phrase.trim();
  if (!clean) continue;
  const slug = slugify(clean);
  const mp3File = join(outDir, `${slug}.mp3`);
  const relativeUrl = `/audio/da/${slug}.mp3`;

  // Map both the exact text and the lowercase version
  manifest[clean.toLowerCase()] = relativeUrl;
  manifest[clean.toLowerCase().replace(/[.,!?;:]/g, "")] = relativeUrl;

  if (!existsSync(mp3File)) {
    let success = false;
    for (let attempt = 1; attempt <= 3; attempt++) {
      try {
        console.log(`Rendering [${clean}] -> ${slug}.mp3 (attempt ${attempt})`);
        const cmd = `${uvx} edge-tts --voice da-DK-ChristelNeural --text "${clean.replace(/"/g, '\\"')}" --write-media "${mp3File}"`;
        execSync(cmd, { stdio: "inherit" });
        success = true;
        break;
      } catch (err) {
        console.error(`Attempt ${attempt} failed for "${clean}":`, err.message);
        execSync("sleep 1");
      }
    }
  } else {
    console.log(`Cached: ${slug}.mp3`);
  }
}

// Write the audio manifest
writeFileSync(join(outDir, "manifest.json"), JSON.stringify(manifest, null, 2));
console.log("Audio manifest written to public/audio/da/manifest.json");

writeFileSync(
  join(process.cwd(), "src/components/tools/lingua/audioManifest.ts"),
  `// Auto-generated by scripts/generate-audio.mjs - DO NOT EDIT MANUALLY
export const NATIVE_AUDIO_CLIPS: Record<string, Record<string, string>> = {
  da: ${JSON.stringify(manifest, null, 2)},
};
`
);
console.log("TypeScript audio manifest written to src/components/tools/lingua/audioManifest.ts");
