name: Docker Slim

#Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  build:
    # run only when the upstream workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }} and github.repository_owner == 'micheletizzani'
    runs-on: ubuntu-latest

    # give permission to write packages (GHCR)
    permissions:
      contents: read
      packages: write

    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: update docker-compose
        shell: bash
        run: |
          sed -i "s|\.:|${{ github.workspace }}:|g" ${{ github.workspace }}/docker-compose-slim.yml
          cat ${{ github.workspace }}/docker-compose-slim.yml

      - uses: kitabisa/docker-slim-action@v1.0.3
        env:
          DSLIM_PULL: true
          DSLIM_COMPOSE_FILE: ${{ github.workspace }}/docker-compose-slim.yml
          DSLIM_TARGET_COMPOSE_SVC: jekyll
          DSLIM_CONTINUE_AFTER: signal
        with:
          target: ghcr.io/${{ github.repository_owner }}/al-folio
          tag: "slim"

      # Push to GHCR
      - run: docker image push ghcr.io/${{ github.repository_owner }}/al-folio:slim
